<Project>
    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(APPVEYOR)' == 'True'">
        <RestoreLockedMode>true</RestoreLockedMode>
    </PropertyGroup>
</Project>
