<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq.Sequences" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hangfire.Core\Hangfire.Core.csproj" />
  </ItemGroup>

  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Cronos'">
        <Aliases>ReferencedCronos</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
</Project>
