<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <NoWarn>0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hangfire.Core\Hangfire.Core.csproj" />
    <ProjectReference Include="..\..\src\Hangfire.SqlServer\Hangfire.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Hangfire.SqlServer.Msmq\Hangfire.SqlServer.Msmq.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSMQ.Messaging" Version="1.0.4" />
  </ItemGroup>

</Project>
