<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <NoWarn>0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" NoWarn="NU1902" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.7" NoWarn="NU1902" />
    <PackageReference Include="Dapper" Version="2.1.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hangfire.Core\Hangfire.Core.csproj" />
    <ProjectReference Include="..\..\src\Hangfire.SqlServer\Hangfire.SqlServer.csproj" />
  </ItemGroup>

  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Dapper'">
        <Aliases>ReferencedDapper</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
</Project>
